### ISSUE TITLE
Esup end of file error

### ISSUE THREAD

**Issue by jschaf** [jschaf/esup#22]
It errors out on https://github.com/dertuxmalwieder/My-Emacs-config/blob/master/.emacs

Reported by http://www.reddit.com/r/emacs/comments/32oufa/emacs_245_startup_time/

**Comment by dertuxmalwieder** [comment]
Additional info: It fails on 25.0.x, but still this shouldn't be the reason for this error.

**Comment by jschaf** [comment]
I'm not sure, https://github.com/jschaf/esup/issues/20 is the exact same problem on Emacs 25

**Comment by dertuxmalwieder** [comment]
Oh, OK. So it's not me. :-)

**Comment by joedicastro** [comment]
I have the same problem, 24.5.1 version here.

**Comment by jschaf** [comment]
Does it consistently fail?  I'm having trouble reproducing it now.

**Comment by dertuxmalwieder** [comment]
It seems to work on Mac OS X. I reported the bug with the Windows build.

**Comment by joedicastro** [comment]
In my case, yes, fails always
I use an Emacs 24.5.1 in Arch Linux with a 64bits kernel (3.19.3).

**Comment by jschaf** [comment]
I pushed a fix for whitespace.  Can you all see if it resolved your issues?

**Comment by joedicastro** [comment]
I still have the problem, but this time I have also the diagnostic.

This is the `*Messages*` buffer in the esup child client:

```
For information about GNU Emacs and the GNU system, type C-h C-a.
Debug on Error enabled globally
esup: loading /home/joedicastro/.emacs.d/init.el
Followed link to /home/joedicastro/dotfiles/emacs/init.el
esup: loading /home/joedicastro/.emacs.d/elpa/diminish-20091203.1012/diminish.elc
esup-child-profile-sexp: End of file during parsing
```

The process alwasys stop (in my case) when the esup child process try to load the `diminisch.elc` byte-compiled file of the `diminish` package. If I delete that `.elc` file all works fine again. I hope that helps you. To me seems a clear problem with the parser.

**Comment by jschaf** [comment]
Okay, it looks like a problem with .elc files.  I haven't really tested parsing against them, so I'll take a look at that.

**Comment by manuel-uberti** [comment]
Any news on this one? Still not working for me on Emacs 25.0.50.1, it stops at diminish.elc
```
LOG: profiling sexp /home/manuel/.emacs.d/init.el:49 (require 'diminish)

LOG: loading /home/manuel/.emacs.d/elpa/diminish-20091203.1012/diminish.elc
```

**Comment by jschaf** [comment]
I have it on my todo list.  Work has been kinda crazy.  I'll take another
look tonight.

**Comment by immerrr** [comment]
Same here, chokes on `diminish.elc`. Any luck with the issue?

**Comment by jschaf** [comment]
I have a hunch that the issue is `forward-sexp` on byte-code.  I'll add some tests to see if I can narrow the issue.

**Comment by manuel-uberti** [comment]
Thanks.

**Comment by cheshirecatalyst** [comment]
Any word on this? I just ran in to it.

**Comment by jschaf** [comment]
Are you on the latest version?  I think disabling debugging in https://github.com/jschaf/esup/commit/1b17a0f23b7044484061e5b52f246939c68181d8 might have fixed it, but I haven't tested it.

**Comment by cheshirecatalyst** [comment]
@jschaf 20160716.23 freshly installed same EOF on diminish

**Comment by jschaf** [comment]
Sorry, been busy at work.  I'll see if I can narrow it down tonight.

**Comment by jschaf** [comment]
Pretty sure I found the bug.

```
(defvar ahhhhhhhhhhh "%" (#$ . 1))
```

My parsing logic looks like it fails on percent signs.  Probably interacting weirdly with `format`.  Should have a fix in the next few days.

**Comment by jschaf** [comment]
The percent sign was a red herring.  It was me not skipping dynamic docstrings at the beginning of a .elc file.  I can parse diminish.elc now.

Should be fixed in https://github.com/jschaf/esup/commit/4028431ad3f9d6682b9afb6888d678b56617e5f4.

Let me know if it works for you.

**Comment by dotmilk** [comment]
@jschaf Works wonderfully. Thank you.

**Comment by jschaf** [comment]
Only took a year and some change, but I think we're good to close this.
